server:
  port: 8300

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nkchauhan003/test-config
          default-label: main
          clone-on-start: true

eureka:
  client:
     service-url.default-zone: http://localhost:8761/eureka